# Generated by Django 3.2.5 on 2021-08-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210824_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='messages',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='nom',
            new_name='name',
        ),
    ]
