# Generated by Django 3.2.5 on 2021-08-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20210821_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='auteurs',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
