# Generated by Django 3.2.5 on 2021-08-28 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_publication_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='background',
            name='date_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='background',
            name='type',
            field=models.CharField(choices=[('A', 'Activités'), ('C', 'Compétences')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
