# Generated by Django 3.2.5 on 2021-08-28 23:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_auto_20210828_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
