# Generated by Django 3.2.5 on 2021-09-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_background_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='presentation',
            field=models.TextField(),
        ),
    ]
