# Generated by Django 3.2.5 on 2021-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('MD', 'Madame'), ('MLLE', 'Mademoiselle'), ('M', 'Monsieur')], max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('profession', models.CharField(max_length=255)),
                ('niveau_etude', models.CharField(choices=[('B', 'Bac'), ('B1', 'Bac+1'), ('B2', 'Bac+2'), ('L', 'Licence'), ('M', 'Master'), ('D', 'Doctorat')], max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('verify_password', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
            },
        ),
    ]
