# Generated by Django 3.2.5 on 2021-08-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210821_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password_foorgot',
            new_name='password_forgot',
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='niveau_etude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='profession',
            field=models.CharField(max_length=200),
        ),
    ]
