# Generated by Django 3.2.5 on 2021-08-27 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image_website')),
                ('description_image', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image_website')),
                ('status', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('messages', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='image_website')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AlterModelOptions(
            name='liens_sociaux',
            options={'verbose_name': 'Liens_sociaux', 'verbose_name_plural': 'Liens_sociaux'},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='description',
            new_name='citation',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='profession',
            new_name='profession_deux',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='photo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='image_website'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='profession_un',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
