# Generated by Django 3.2.5 on 2021-08-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_coursses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='website_image')),
                ('description_image', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner_coursses',
                'verbose_name_plural': 'Banner_coursses',
            },
        ),
        migrations.CreateModel(
            name='Banner_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='website_image')),
                ('status', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner_skills',
                'verbose_name_plural': 'Banner_skills',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('messages', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Gallerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='website_image')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallerie',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AlterModelOptions(
            name='about_detail',
            options={'verbose_name': 'About_detail', 'verbose_name_plural': 'About_details'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='liens_sociaux',
            options={'verbose_name': 'Liens_sociaux', 'verbose_name_plural': 'Liens_sociaux'},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='profession',
            new_name='profession_deux',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='citation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='photo',
            field=models.FileField(default=1, upload_to='website_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='profession_un',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liens_sociaux',
            name='icone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liens_sociaux',
            name='lien',
            field=models.TextField(blank=True, null=True),
        ),
    ]
