# Generated by Django 3.2.5 on 2021-08-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210824_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_detail',
        ),
    ]
