# Generated by Django 3.2.7 on 2021-09-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210903_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_detail',
        ),
    ]
