# Generated by Django 3.2.7 on 2021-09-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_siteweb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liens_sociaux',
            name='nom',
        ),
    ]
