# Generated by Django 3.2.7 on 2021-09-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_liens_sociaux_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='liens_sociaux',
            name='icone',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
