# Generated by Django 3.2.7 on 2021-09-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_liens_sociaux_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liens_sociaux',
            name='icone',
            field=models.CharField(max_length=200),
        ),
    ]
