# Generated by Django 3.2.5 on 2021-08-31 00:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_alter_training_matieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='matieres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'aaa'), (2, 'bbb'), (3, 'ccc')], max_length=5),
        ),
    ]
