# Generated by Django 3.2.5 on 2021-08-31 01:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_alter_training_matieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='matieres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Dosimétrie générale'), (2, 'Radioprotection')], max_length=3),
        ),
    ]
