# Generated by Django 3.2.5 on 2021-08-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_alter_training_matieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date_debut',
            field=models.DateField(verbose_name='Dte de début'),
        ),
        migrations.AlterField(
            model_name='training',
            name='date_fin',
            field=models.DateField(verbose_name='Date de fin'),
        ),
    ]
