# Generated by Django 3.2.5 on 2021-08-31 01:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0007_alter_training_date_debut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterField(
            model_name='training',
            name='intitule',
            field=models.CharField(max_length=100, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='training',
            name='matieres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Dosimétrie générale'), (2, 'Radioprotection')], max_length=3, verbose_name='Matières'),
        ),
        migrations.AlterField(
            model_name='training',
            name='statut',
            field=models.CharField(choices=[('C', 'En cours'), ('A', 'En attente'), ('T', 'Terminé')], max_length=1, verbose_name='Etat'),
        ),
    ]
